# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'vk-market' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'VK-ios-sdk'
  pod 'SDWebImage'
  pod 'MBProgressHUD', '~> 1.2.0'

end

